# exception
* exception[meta header]
* std[meta namespace]
* class[meta id-type]

```cpp
namespace std {
  class exception;
}
```

## ТдѓУдЂ
`exception`сѓ»сЃЕсѓ╣сЂ»сђЂТеЎТ║ќсЃЕсѓцсЃќсЃЕсЃфсЂїТЈљСЙЏсЂЎсѓІтЁесЂдсЂ«СЙІтцќсѓ»сЃЕсѓ╣сЂ«тЪ║т║Ћсѓ»сЃЕсѓ╣сЂДсЂѓсѓІсђѓ

ТеЎТ║ќсЃЕсѓцсЃќсЃЕсЃфсЂФсѓѕсЂБсЂджђЂтЄ║сЂЋсѓїсѓІСЙІтцќсѓфсЃќсѓИсѓДсѓ»сЃѕсЂ«сѓ»сЃЕсѓ╣сЂ»тЁесЂдсђЂсЂЊсЂ«сѓ»сЃЕсѓ╣сЂІсѓЅТ┤ЙућЪсЂЎсѓІсђѓсЂЌсЂЪсЂїсЂБсЂдсђЂТеЎТ║ќсЂ«СЙІтцќсЂ»тЁесЂдсЂЊсЂ«сѓ»сЃЕсѓ╣сЂДТЇЋТЇЅсЂДсЂЇсѓІсђѓ


## сЃАсЃ│сЃљжќбТЋ░

| тљЇтЅЇ | УфгТўј | т»Йт┐юсЃљсЃ╝сѓИсЃДсЃ│ |
|----------------------------------------|---------------------------------------------|-------|
| `exception() noexcept;`<br/>`exception(const exception&) noexcept;` | сѓ│сЃ│сѓ╣сЃѕсЃЕсѓ»сѓ┐ | |
| `virtual ~exception();` | сЃЄсѓ╣сЃѕсЃЕсѓ»сѓ┐ | |
| `exception& operator=(const exception&) noexcept;` | С╗БтЁЦТ╝ћу«Ќтљ | |
| `virtual const char* what() const noexcept;` | т«ЪУБЁт«џуЙЕсЂ«сѓесЃЕсЃ╝тєЁт«╣сѓњтЈќтЙЌсЂЎсѓІ | |


## СЙІ
```cpp example
#include <iostream>
#include <exception>
#include <stdexcept> // std::runtime_error

int main()
{
  try {
    bool is_error = true;
    if (is_error) { // сЂфсѓЊсѓЅсЂІсЂ«сѓесЃЕсЃ╝сЂїуЎ║ућЪсЂЌсЂЪ
      throw std::runtime_error("error!"); // СЙІтцќжђЂтЄ║
    }
  }
  catch (std::exception& e) {
    // СЙІтцќсѓњТЇЋТЇЅ
    // сѓесЃЕсЃ╝уљєућ▒сѓњтЄ║тіЏсЂЎсѓІ
    std::cout << e.what() << std::endl;
  }
}
```

### тЄ║тіЏ
```
error!
```


## тЈѓуЁД

