<!doctype html>
<html class="cpprefjp" lang="ja" itemscope="" itemtype="http://schema.org/WebPage">
    <head>
        
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NXNBNVBTJS"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-NXNBNVBTJS');
</script>


        <meta charset="UTF-8">

        <title>uncaught_exception - cpprefjp C++日本語リファレンス</title>

        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="keywords" content="
  C++,標準ライブラリ,リファレンス,ドキュメント,STL,std,exception,std,function,cpp17deprecated
">
        <meta name="title" content="uncaught_exception - cpprefjp C++日本語リファレンス" />
        <meta itemprop="name" content="uncaught_exception - cpprefjp C++日本語リファレンス" />
        <meta property="og:title" content="uncaught_exception - cpprefjp C++日本語リファレンス" />
        <meta property="og:url" content="https://cpprefjp.github.io/reference/exception/uncaught_exception.html" />
        <meta property="og:site_name" content="cpprefjp - C++日本語リファレンス" />
        <meta property="og:type" content="article" />
        <meta property="og:description" content="キャッチされていない例外があるかどうかを判定する。" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content="uncaught_exception - cpprefjp C++日本語リファレンス" />
        <meta name="twitter:url" content="https://cpprefjp.github.io/reference/exception/uncaught_exception.html" />
        <meta name="twitter:description" content="キャッチされていない例外があるかどうかを判定する。" />

        
  <link rel="alternate" type="application/atom+xml" title="Atom" href="https://cpprefjp.github.io/rss.xml" />


<link rel="apple-touch-icon" sizes="180x180" href="../../static/favicons/apple-touch-icon.png?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<link rel="icon" type="image/png" sizes="32x32" href="../../static/favicons/favicon-32x32.png?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<link rel="icon" type="image/png" sizes="16x16" href="../../static/favicons/favicon-16x16.png?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<link rel="manifest" href="../../manifest.json?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<meta name="theme-color" content="#f5f8fc">

<link rel="stylesheet" href="../../static/pygments/default.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa">
<!-- <link rel="stylesheet" href="../../static/css/root.css"> -->

        
  


<link href="../../static/kunai/css/kunai-stage-0.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa" rel="stylesheet">
<link href="../../static/kunai/css/kunai-stage-1.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa" rel="stylesheet">
<link href="../../static/kunai/css/kunai-stage-2.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa" rel="stylesheet">
<link href="../../static/kunai/css/kunai-stage-3.css?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa" rel="stylesheet">

<script type="text/javascript" src="../../static/kunai/js/kunai-vendor.js?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa"></script>
<script type="text/javascript" src="../../static/kunai/js/kunai.js?cachebust=8057d990dd61d47f1f176cd500c679183b81aeaa"></script>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var kn = new Kunai;
    kn.cpprefjp();
  });
</script>

    </head>
    <body>
<header data-kunai-mdinfo="{&#34;meta&#34;: {&#34;header&#34;: [&#34;exception&#34;], &#34;namespace&#34;: [&#34;std&#34;], &#34;id-type&#34;: [&#34;function&#34;], &#34;cpp&#34;: [&#34;cpp17deprecated&#34;, &#34;cpp20removed&#34;]}, &#34;sources&#34;: [{&#34;id&#34;: &#34;a5a301f1411fffc91af5ac6870117cbb2acd9980&#34;, &#34;source&#34;: &#34;#include &lt;iostream&gt;\n#include &lt;exception&gt;\n\nstruct X {\n  ~X()\n  {\n    bool has_uncaught = std::uncaught_exception();\n    std::cout &lt;&lt; std::boolalpha &lt;&lt; has_uncaught &lt;&lt; std::endl;\n  }\n};\n\nint main()\n{\n  try {\n    X x;\n    throw std::exception();\n  }\n  catch (std::exception&amp; e) {\n    std::cout &lt;&lt; \&#34;catch\&#34; &lt;&lt; std::endl;\n  }\n}\n&#34;}], &#34;page_id&#34;: [&#34;reference&#34;, &#34;exception&#34;, &#34;uncaught_exception&#34;]}">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="../../index.html">
          <div class="title-wrapper clearfix">
            <div class="title">cpprefjp - C++日本語リファレンス</div>
          </div>
        </a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <div class="google-search">
              
  
<script>
  (function() {
    var cx = '013316413321391058734:ji_u66hl7hq';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<div class="gcse-search"></div>


            </div>
          </li>
          <li>
  <a href="https://github.com/cpprefjp/site">GitHub Project</a>
</li>
        </ul>
      </div>
    </div>
  </nav>
</header>

        <main id="main" role="main">
            <div class="container-fluid">
<div class="row">
  <div class="col-sm-9 col-sm-push-3" itemscope itemtype="http://schema.org/Article">
    <div class="row">
      <div class="col-sm-12 google-search-result">
        <gcse:searchresults></gcse:searchresults>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 content-header">
        
  <ol class="breadcrumb">
    
      <li  itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            <a href="../../index.html" itemprop="url">
              
                <i class="fa fa-fw fa-home"></i>
              
            </a>
          
        </span>
      </li>
    
      <li  itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            <a href="../../reference.html" itemprop="url">
              
                <span itemprop="name">リファレンス</span>
              
            </a>
          
        </span>
      </li>
    
      <li  itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            <a href="../../reference/exception.html" itemprop="url">
              
                <span itemprop="name">exception</span>
              
            </a>
          
        </span>
      </li>
    
      <li class="active" itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            
              <span itemprop="name">uncaught_exception</span>
            
          
        </span>
      </li>
    
  </ol>
  <div class="crsearch"></div>

      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 edit-button">
        
  
    <p class="text-right"><small>
      最終更新日時(UTC):
      <span itemprop="datePublished" content="2019-01-19T08:18:34">
        2019年01月19日 08時18分34秒
      </span>
      <br/>
      <span itemprop="author" itemscope itemtype="http://schema.org/Person">
        <span itemprop="name">onihusube</span>
      </span>
      が更新
    </small></p>
  

        <p class="text-right">
          <a class="history" target="_blank" href="https://github.com/cpprefjp/site/commits/master/reference/exception/uncaught_exception.md">
            <span class="fa fa-fw fa-clock-o fa-flip-horizontal"></span>履歴
          </a>
          <a class="edit" target="_blank" href="https://github.com/cpprefjp/site/edit/master/reference/exception/uncaught_exception.md">
            <span class="fa fa-fw fa-pencil"></span>編集
          </a>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 content-body">
        
  <div class="identifier-type">function</div><div class="header">&lt;exception&gt;</div><h1 itemprop="name"><span class="namespace" title="namespace std">std::</span><span class="token">uncaught_exception</span><span class="cpp cpp17deprecated text-warning" title="C++17で非推奨">(C++17で非推奨)</span><span class="cpp cpp20removed text-danger" title="C++20で削除">(C++20で削除)</span></h1>
<div itemprop="articleBody"><p><div class="codehilite"><pre><span></span><code><span class="k">namespace</span> <span class="n">std</span> <span class="p">{</span>
  <span class="kt">bool</span> <span class="n">uncaught_exception</span><span class="p">()</span> <span class="k">throw</span><span class="p">();</span>  <span class="c1">// C++03</span>
  <span class="kt">bool</span> <span class="nf">uncaught_exception</span><span class="p">()</span> <span class="k">noexcept</span><span class="p">;</span> <span class="c1">// C++11</span>
<span class="p">}</span>
</code></pre></div>
</p>
<p>この機能はC++17から非推奨となり、C++20で削除された。代わりに<code><a href="uncaught_exceptions.html">std::uncaught_exceptions()</a></code>を使用すること。</p>
<h2>概要</h2>
<p>キャッチされていない<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>があるかどうかを判定する。</p>
<h2><a class="cpprefjp-defined-word" data-desc="関数呼び出し式の評価結果となるオブジェクト・値">戻り値</a></h2>
<p><a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>オブジェクトが生成され、スローされてからキャッチするまでの間に<code>true</code>を返す。</p>
<p>また、明示的に<code><a href="terminate.html">terminate()</a></code>を呼び出し、実際に呼び出されるまでの間に<code>true</code>を返す。</p>
<p>具体的には、<code>try</code>ブロック中で作られたオブジェクトのデストラクタや、スタック巻き戻し(unwind)中のデストラクタ、<code><a href="terminate.html">terminate()</a></code>の場合は生存している全てのオブジェクトのデストラクタで<code>true</code>になる。</p>
<h2><a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a></h2>
<p>投げない</p>
<h2>例</h2>
<p><div class="yata" id="a5a301f1411fffc91af5ac6870117cbb2acd9980"><div class="codehilite"><pre><span></span><code><span class="cp">#include</span> <span class="cpf"><a href="../iostream.html">&lt;iostream&gt;</a></span><span class="cp"></span>
<span class="cp">#include</span> <span class="cpf"><a href="../exception.html">&lt;exception&gt;</a></span><span class="cp"></span>

<span class="k">struct</span> <span class="n">X</span> <span class="p">{</span>
  <span class="o">~</span><span class="n">X</span><span class="p">()</span>
  <span class="p">{</span>
    <span class="kt">bool</span> <span class="n">has_uncaught</span> <span class="o">=</span> <span class="n"><span style="color:#ff0000">std::uncaught_exception</span></span><span class="p">();</span>
    <span class="n"><a href="../iostream/cout.html">std::cout</a></span> <span class="o">&lt;&lt;</span> <span class="n"><a href="../ios/boolalpha.html">std::boolalpha</a></span> <span class="o">&lt;&lt;</span> <span class="n">has_uncaught</span> <span class="o">&lt;&lt;</span> <span class="n"><a href="../ostream/endl.html">std::endl</a></span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">};</span>

<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span>
<span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="n">X</span> <span class="n">x</span><span class="p">;</span>
    <span class="k">throw</span> <span class="n"><a href="exception.html">std::exception</a></span><span class="p">();</span>
  <span class="p">}</span>
  <span class="k">catch</span> <span class="p">(</span><span class="n"><a href="exception.html">std::exception</a></span><span class="o">&amp;</span> <span class="n">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="n"><a href="../iostream/cout.html">std::cout</a></span> <span class="o">&lt;&lt;</span> <span class="s">"catch"</span> <span class="o">&lt;&lt;</span> <span class="n"><a href="../ostream/endl.html">std::endl</a></span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre></div>
</div></p>
<h3>出力</h3>
<p><pre><code>true
catch
</code></pre></p>
<h2>参照</h2>
<ul>
<li><a href="http://www.gotw.ca/gotw/047.htm" target="_blank">GotW #47 Uncaught Exceptions</a></li>
<li><a href="http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#475" target="_blank">CWG Issue 475. When is <code>std::uncaught_exception()</code> true? (take 2)</a></li>
<li><a href="http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0619r4.html" target="_blank">P0619R4 Reviewing deprecated facilities of C++17 for C++20</a></li>
</ul></div>

      </div>
    </div>
  </div>
  
  
    <div id="sidebar" class="col-sm-3 col-sm-pull-9">
    </div>
  

</div>
            </div>
        </main>
<footer class="footer navbar navbar-default">
  <div class="container-fluid">
    <p><small>
      本サイトの情報は、
        <a href="https://creativecommons.org/licenses/by/3.0/deed.ja" rel="nofollow">クリエイティブ・コモンズ 表示 3.0 非移植 ライセンス(CC BY)</a>
      の下に提供されています。
    </small></p>
  </div>
</footer>
    </body>
</html>