<!doctype html>
<html class="cpprefjp" lang="ja" itemscope="" itemtype="http://schema.org/WebPage">
    <head>
        
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NXNBNVBTJS"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-NXNBNVBTJS');
</script>


        <meta charset="UTF-8">

        <title>stdexcept - cpprefjp C++日本語リファレンス</title>

        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="keywords" content="
  C++,標準ライブラリ,リファレンス,ドキュメント,STL,std,stdexcept
">
        <meta name="title" content="stdexcept - cpprefjp C++日本語リファレンス" />
        <meta itemprop="name" content="stdexcept - cpprefjp C++日本語リファレンス" />
        <meta property="og:title" content="stdexcept - cpprefjp C++日本語リファレンス" />
        <meta property="og:url" content="https://cpprefjp.github.io/reference/stdexcept.html" />
        <meta property="og:site_name" content="cpprefjp - C++日本語リファレンス" />
        <meta property="og:type" content="article" />
        <meta property="og:description" content="&amp;lt;stdexcept&amp;gt;stdexcept &amp;lt;stdexcept&amp;gt;ヘッダは、標準的な例外クラスを提供する。 これらの例外クラスは、標準ライブラリ内でも使用されている。 これらのクラス群に反映されているエラーモデルでは、エラーは「実行時エラー (runtime error) 」と「論理エラー (logic error) 」との２つに大別される。 論理エラーを区別するための性質は" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content="stdexcept - cpprefjp C++日本語リファレンス" />
        <meta name="twitter:url" content="https://cpprefjp.github.io/reference/stdexcept.html" />
        <meta name="twitter:description" content="&amp;lt;stdexcept&amp;gt;stdexcept &amp;lt;stdexcept&amp;gt;ヘッダは、標準的な例外クラスを提供する。 これらの例外クラスは、標準ライブラリ内でも使用されている。 これらのクラス群に反映されているエラーモデルでは、エラーは「実行時エラー (runtime error) 」と「論理エラー (logic error) 」との２つに大別される。 論理エラーを区別するための性質は" />

        
  <link rel="alternate" type="application/atom+xml" title="Atom" href="https://cpprefjp.github.io/rss.xml" />


<link rel="apple-touch-icon" sizes="180x180" href="../static/favicons/apple-touch-icon.png?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20">
<link rel="icon" type="image/png" sizes="32x32" href="../static/favicons/favicon-32x32.png?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20">
<link rel="icon" type="image/png" sizes="16x16" href="../static/favicons/favicon-16x16.png?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20">
<link rel="manifest" href="../manifest.json?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20">
<meta name="theme-color" content="#f5f8fc">

<link rel="stylesheet" href="../static/pygments/default.css?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20">
<!-- <link rel="stylesheet" href="../static/css/root.css"> -->

        
  


<link href="../static/kunai/css/kunai-stage-0.css?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20" rel="stylesheet">
<link href="../static/kunai/css/kunai-stage-1.css?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20" rel="stylesheet">
<link href="../static/kunai/css/kunai-stage-2.css?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20" rel="stylesheet">
<link href="../static/kunai/css/kunai-stage-3.css?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20" rel="stylesheet">

<script type="text/javascript" src="../static/kunai/js/kunai-vendor.js?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20"></script>
<script type="text/javascript" src="../static/kunai/js/kunai.js?cachebust=77dc81f1a0fc7ba1be2bc06336653840aa3f2e20"></script>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var kn = new Kunai;
    kn.cpprefjp();
  });
</script>

    </head>
    <body>
<header data-kunai-mdinfo="{&#34;meta&#34;: {&#34;header&#34;: [&#34;stdexcept&#34;]}, &#34;sources&#34;: [{&#34;id&#34;: &#34;57c1810dc3f9923866fa7027e9f688b557b80778&#34;, &#34;source&#34;: &#34;#include &lt;stdexcept&gt;\n#include &lt;iostream&gt;\n#include &lt;cstdlib&gt;\n\nvoid f()\n{\n  // \u4f8b\u5916\u3092\u6295\u3052\u308b\n  throw std::logic_error(\&#34;an exception occurred\&#34;);\n}\n\nint main()\n{\n  try {\n    f();\n  }\n  catch (const std::logic_error&amp; e) {\n    // \u4f8b\u5916\u304c\u767a\u751f\u3057\u305f\uff01\n    std::cout &lt;&lt; e.what() &lt;&lt; std::endl;\n    std::exit(1);\n  }\n}\n&#34;}], &#34;page_id&#34;: [&#34;reference&#34;, &#34;stdexcept&#34;]}">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="../index.html">
          <div class="title-wrapper clearfix">
            <div class="title">cpprefjp - C++日本語リファレンス</div>
          </div>
        </a>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <div class="google-search">
              
  
<script>
  (function() {
    var cx = '013316413321391058734:ji_u66hl7hq';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<div class="gcse-search"></div>


            </div>
          </li>
          <li>
  <a href="https://github.com/cpprefjp/site">GitHub Project</a>
</li>
        </ul>
      </div>
    </div>
  </nav>
</header>

        <main id="main" role="main">
            <div class="container-fluid">
<div class="row">
  <div class="col-sm-9 col-sm-push-3" itemscope itemtype="http://schema.org/Article">
    <div class="row">
      <div class="col-sm-12 google-search-result">
        <gcse:searchresults></gcse:searchresults>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 content-header">
        
  <ol class="breadcrumb">
    
      <li  itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            <a href="../index.html" itemprop="url">
              
                <i class="fa fa-fw fa-home"></i>
              
            </a>
          
        </span>
      </li>
    
      <li  itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            <a href="../reference.html" itemprop="url">
              
                <span itemprop="name">リファレンス</span>
              
            </a>
          
        </span>
      </li>
    
      <li class="active" itemscope itemtype="http://www.schema.org/SiteNavigationElement">
        <span>
          
            
              <span itemprop="name">stdexcept</span>
            
          
        </span>
      </li>
    
  </ol>
  <div class="crsearch"></div>

      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 edit-button">
        
  
    <p class="text-right"><small>
      最終更新日時(UTC):
      <span itemprop="datePublished" content="2025-04-03T07:38:08">
        2025年04月03日 07時38分08秒
      </span>
      <br/>
      <span itemprop="author" itemscope itemtype="http://schema.org/Person">
        <span itemprop="name">Akira Takahashi</span>
      </span>
      が更新
    </small></p>
  

        <p class="text-right">
          <a class="history" target="_blank" href="https://github.com/cpprefjp/site/commits/master/reference/stdexcept.md">
            <span class="fa fa-fw fa-clock-o fa-flip-horizontal"></span>履歴
          </a>
          <a class="edit" target="_blank" href="https://github.com/cpprefjp/site/edit/master/reference/stdexcept.md">
            <span class="fa fa-fw fa-pencil"></span>編集
          </a>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 content-body">
        
  <div class="header">&lt;stdexcept&gt;</div><h1 itemprop="name"><span class="token">stdexcept</span></h1>
<div itemprop="articleBody"><p><code>&lt;stdexcept&gt;</code>ヘッダは、標準的な<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>クラスを提供する。<br />
これらの<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>クラスは、標準ライブラリ内でも使用されている。</p>
<p>これらのクラス群に反映されているエラーモデルでは、エラーは「実行時エラー (runtime error) 」と「論理エラー (logic error) 」との２つに大別される。<br />
論理エラーを区別するための性質は、それがプログラムの内部的論理の誤りに起因することである。理論的には、それらは予め避けることができる。<br />
対して、実行時エラーはプログラムの制御の及ばない事象に起因する。それらを前もって簡単に予見することはできない。</p>
<p>このヘッダで提供される<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>クラスは以下の表の通りである。以下のクラスは全て、<code>std</code>名前空間で提供される。</p>
<table border="1" bordercolor="#888" style="border-collapse:collapse">
<thead>
<tr>
<th>名前</th>
<th>説明</th>
<th>対応バージョン</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>logic_error</code></td>
<td>プログラムの実行前に検出可能なエラー（論理エラー）を示す</td>
<td></td>
</tr>
<tr>
<td><code>domain_error</code></td>
<td>定義域エラーを示す</td>
<td></td>
</tr>
<tr>
<td><code>invalid_argument</code></td>
<td>不正な引数を示す</td>
<td></td>
</tr>
<tr>
<td><code>length_error</code></td>
<td>長すぎるオブジェクトを作ろうとしたことを示す</td>
<td></td>
</tr>
<tr>
<td><code>out_of_range</code></td>
<td>引数が許容範囲外であることを示す</td>
<td></td>
</tr>
<tr>
<td><code>runtime_error</code></td>
<td>プログラム実行時にのみ検出可能なエラー（実行時エラー）を示す</td>
<td></td>
</tr>
<tr>
<td><code>range_error</code></td>
<td>内部計算によって、値が範囲外になったことを示す（値域エラー）</td>
<td></td>
</tr>
<tr>
<td><code>overflow_error</code></td>
<td>数値計算の結果がオーバーフローしたことを示す</td>
<td></td>
</tr>
<tr>
<td><code>underflow_error</code></td>
<td>数値計算の結果がアンダーフローしたことを示す</td>
<td></td>
</tr>
</tbody>
</table>
<p><a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>クラスには継承関係があり、以下の箇条書きの階層構造で示す。</p>
<ul>
<li><code><a href="exception/exception.html">exception</a></code><ul>
<li><code>logic_error</code><ul>
<li><code>domain_error</code></li>
<li><code>invalid_argument</code></li>
<li><code>length_error</code></li>
<li><code>out_of_range</code></li>
</ul>
</li>
<li><code>runtime_error</code><ul>
<li><code>range_error</code></li>
<li><code>overflow_error</code></li>
<li><code>underflow_error</code></li>
</ul>
</li>
</ul>
</li>
</ul>
<p><code><a href="exception/exception.html">exception</a></code>クラスを除く9つのクラスは、すべて同じ<code>public</code>メンバ関数をもつ。 </p>
<p>クラス名を<code>T</code>とすると、以下の<code>public</code>メンバ関数をもつ。</p>
<h2>メンバ関数</h2>
<table border="1" bordercolor="#888" style="border-collapse:collapse">
<thead>
<tr>
<th>名前</th>
<th>説明</th>
<th>対応バージョン</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>explicit T(const <a href="string/basic_string.html">string</a>&amp; what_arg); // C++03</code><br /> <code>constexpr explicit T(const <a href="string/basic_string.html">string</a></code>`&amp; what_arg); // C++26</td>
<td>指定したメッセージを持つ<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>オブジェクトを生成する</td>
<td></td>
</tr>
<tr>
<td><code>explicit T(const char* what_arg); // C++11</code><br /> <code>constexpr explicit T(const char* what_arg); // C++26</code></td>
<td>指定したメッセージを持つ<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>オブジェクトを生成する</td>
<td>C++11</td>
</tr>
<tr>
<td><code>virtual const char* what() const noexcept; // C++03</code><br /> <code>constexpr virtual const char* what() const noexcept; // C++26</code></td>
<td>メッセージを取得する</td>
<td></td>
</tr>
</tbody>
</table>
<h2>例</h2>
<p>ここでは、簡単な<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>処理の例を示す。</p>
<p><div class="yata" id="57c1810dc3f9923866fa7027e9f688b557b80778"><div class="codehilite"><pre><span></span><code><span class="cp">#include</span> <span class="cpf"><a href="">&lt;stdexcept&gt;</a></span><span class="cp"></span>
<span class="cp">#include</span> <span class="cpf"><a href="iostream.html">&lt;iostream&gt;</a></span><span class="cp"></span>
<span class="cp">#include</span> <span class="cpf"><a href="cstdlib.html">&lt;cstdlib&gt;</a></span><span class="cp"></span>

<span class="kt">void</span> <span class="nf">f</span><span class="p">()</span>
<span class="p">{</span>
  <span class="c1">// 例外を投げる</span>
  <span class="k">throw</span> <span class="n"><span style="color:#ff0000">std::logic_error</span></span><span class="p">(</span><span class="s">"an exception occurred"</span><span class="p">);</span>
<span class="p">}</span>

<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span>
<span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="n">f</span><span class="p">();</span>
  <span class="p">}</span>
  <span class="k">catch</span> <span class="p">(</span><span class="k">const</span> <span class="n"><span style="color:#ff0000">std::logic_error</span></span><span class="o">&amp;</span> <span class="n">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="c1">// 例外が発生した！</span>
    <span class="n"><a href="iostream/cout.html">std::cout</a></span> <span class="o">&lt;&lt;</span> <span class="n">e</span><span class="p">.</span><span class="n">what</span><span class="p">()</span> <span class="o">&lt;&lt;</span> <span class="n"><a href="ostream/endl.html">std::endl</a></span><span class="p">;</span>
    <span class="n"><a href="cstdlib/exit.html">std::exit</a></span><span class="p">(</span><span class="mi">1</span><span class="p">);</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre></div>
</div></p>
<h2>関連項目</h2>
<ul>
<li><a href="../lang/cpp26/allowing_exception_throwing_in_constant-evaluation.html">C++26 定数評価での例外送出を許可</a></li>
</ul>
<h2>参照</h2>
<ul>
<li><a href="http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#254" target="_blank">LWG Issue 254. Exception types in clause 19 are constructed from <code>std::string</code></a><ul>
<li>C++11から<a class="cpprefjp-defined-word" data-desc="問題が発生したときに、現在実行位置を過去に通過・記録した位置に戻し、文脈情報を添えて紐づけられた処理(例外ハンドラー)を呼び出す仕組み。またはその事態">例外</a>送出の理由として、文字配列を受け取ることを許可した経緯のレポート</li>
</ul>
</li>
<li><a href="https://open-std.org/jtc1/sc22/wg21/docs/papers/2025/p3378r2.html" target="_blank">P3378R2 <code>constexpr</code> exception types</a><ul>
<li>C++26で<code>constexpr</code>対応した</li>
</ul>
</li>
</ul></div>

      </div>
    </div>
  </div>
  
  
    <div id="sidebar" class="col-sm-3 col-sm-pull-9">
    </div>
  

</div>
            </div>
        </main>
<footer class="footer navbar navbar-default">
  <div class="container-fluid">
    <p><small>
      本サイトの情報は、
        <a href="https://creativecommons.org/licenses/by/3.0/deed.ja" rel="nofollow">クリエイティブ・コモンズ 表示 3.0 非移植 ライセンス(CC BY)</a>
      の下に提供されています。
    </small></p>
  </div>
</footer>
    </body>
</html>